## docker build .
## docker run -it <id>      run in interactive mode to input to container
## docker stop <name>
## docker start -ai <name>  start a container in interactive mode for input

FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]